version: 3
services:
    nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    environment:
        - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
        - BACKEND_HOST=${BACKEND_HOST}
        - BACKEND_PORT=${BACKEND_PORT}
    entrypoint: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"